language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
   
